### ISSUE TITLE
Installation fails with recent poetry due to `fasttext` issues

### ISSUE THREAD

**Issue by saevarb** [Proteusiq/luga#13]
Hey!

As is explained in this issue: https://github.com/python-poetry/poetry/issues/6113 trying to install `fasttext` with a recent poetry version fails. This is because `fasttext` does some really funky things and tries to run a global `pip` during install. So this means that building `luga` or using any package that depends on it doesn't work. :/

This means that columbus doesn't build either, since it depends on luga. However, as is outlined in the issue there is a solution: using `fasttext-wheel`.

I pulled down `luga` and `columbus` and updated `luga` to use `fasttext-wheel` instead, and managed to get it to install, which also allowed me to build a new version of `columbus` using the new `luga` build.

**Comment by Proteusiq** [comment]
fixed with #14
